deny = [
    "clippy::all",
    # "clippy::unwrap_used",
    # "clippy::expect_used"
]
warn = [
    "clippy::pedantic",
    "clippy::nursery",
    # "clippy::unwrap_used",
    # "clippy::expect_used",
]
allow = [
    "clippy::missing_errors_doc",
    "clippy::missing_const_for_fn",
    "clippy::unused_async",
]
