version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsletter
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    image: zero2prod
    ports:
      - "8080:8080"
    depends_on:
      - database
