application:
  port: 8080
database:
  port: 5432
  username: "newsletter"
  password: "postgres"
  name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@email.com"
  authorization_token: "secret-token"
