application:
  host: 0.0.0.0
database:
  host: "database" # docker-compose.yml host name for database
email_client:
  base_url: "https://api.sendgrid.com/v3/mail/send" # from SendGrid docs
  sender_email: "satvik@darkmodes.com"
